version: '3'

services:
  # Evolution
  evolution-api1:
    image: atendai/evolution-api:v2.1.1
    container_name: evolution_api1
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - local_net
    volumes:
      - evolution_instances:/evolution/instances
    env_file:
      - .env
    depends_on:
      - postgres_evolution1
      - redis1

  postgres_evolution1:
    image: postgres:16
    restart: always
    command: ["postgres", "-p", "5434"]
    ports:
      - '5434:5434'
    networks:
      - local_net
    volumes:
      - postgres_evolution:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=evolution
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  redis1:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
    networks:
      - local_net

networks:
  local_net:

volumes:
  evolution_instances:
  postgres_evolution:
  redis_data:
